services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: scr-mesh-frontend:latest
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
    command: npm start

  backend:
    build: ./backend
    image: scr-mesh-backend:latest
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/openwisp
      - NODE_ENV=development

  postgres:
    image: postgres:14
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=openwisp

volumes:
  postgres_data: 