services:
  frontend:
    image: ${REGISTRY:-docker.io}/${NAMESPACE:-d1g1talterrain}/scr-mesh-frontend:${TAG:-latest}
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-80}:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    image: ${REGISTRY:-docker.io}/${NAMESPACE:-d1g1talterrain}/scr-mesh-backend:${TAG:-latest}
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/openwisp
      - NODE_ENV=production
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=openwisp

volumes:
  postgres_data: 