services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: ${REGISTRY:-docker.io}/${NAMESPACE:-d1g1talterrain}/scr-mesh-frontend:${TAG:-latest}

  backend:
    build: 
      context: ./backend
      args:
        - NODE_ENV=production
    image: ${REGISTRY:-docker.io}/${NAMESPACE:-d1g1talterrain}/scr-mesh-backend:${TAG:-latest} 